# Generated by Django 3.2.6 on 2021-09-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('dimensions', models.CharField(max_length=15)),
                ('square', models.CharField(max_length=15)),
                ('square1', models.CharField(max_length=15, null=True)),
                ('square2', models.CharField(max_length=15, null=True)),
                ('cost', models.CharField(max_length=15)),
                ('video_url', models.CharField(max_length=20)),
                ('cover', models.CharField(max_length=20, null=True)),
                ('description1', models.TextField(null=True)),
                ('description2', models.TextField(null=True)),
                ('complex', models.TextField(null=True)),
                ('construction', models.CharField(max_length=20)),
                ('brus', models.CharField(max_length=20)),
                ('images_count', models.IntegerField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('slug', models.SlugField(verbose_name='Slug'))
            ],
        ),
        migrations.CreateModel(
            name='Sauna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('dimensions', models.CharField(max_length=15)),
                ('square', models.CharField(max_length=15)),
                ('square1', models.CharField(max_length=15, null=True)),
                ('square2', models.CharField(max_length=15, null=True)),
                ('cost', models.CharField(max_length=15)),
                ('video_url', models.CharField(max_length=20)),
                ('cover', models.CharField(max_length=20, null=True)),
                ('description1', models.TextField(null=True)),
                ('description2', models.TextField(null=True)),
                ('complex', models.TextField(null=True)),
                ('construction', models.CharField(max_length=20)),
                ('brus', models.CharField(max_length=20)),
                ('images_count', models.IntegerField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('slug', models.SlugField(verbose_name='Slug'))
            ],
        ),
    ]
