# Generated by Django 3.2.6 on 2021-09-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='full_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='short_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
