# Generated by Django 3.2.6 on 2021-09-15 09:26

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_auto_20210909_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='SOME SLUG', editable=False, populate_from='full_name'),
        ),
        migrations.AddField(
            model_name='sauna',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='SOME SLUG', editable=False, populate_from='full_name'),
        ),
    ]
