# Generated by Django 3.2.6 on 2021-10-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_auto_20210909_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='complex',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='cover',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='description1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='description2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='square1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='square2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sauna',
            name='complex',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sauna',
            name='cover',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sauna',
            name='description1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sauna',
            name='description2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sauna',
            name='square1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sauna',
            name='square2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
