# Generated by Django 3.2.6 on 2021-10-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_auto_20211021_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='cover',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sauna',
            name='cover',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
