# Generated by Django 3.2.6 on 2021-12-31 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_auto_20211021_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='slug',
            field=models.SlugField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='sauna',
            name='slug',
            field=models.SlugField(max_length=300, unique=True),
        ),
    ]
