# Generated by Django 3.2.6 on 2022-02-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_auto_20211231_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('short_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('dimensions', models.CharField(max_length=15)),
                ('square', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Превью проекта')),
            ],
        ),
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterModelOptions(
            name='sauna',
            options={'ordering': ['-pub_date']},
        ),
    ]
