# Generated by Django 3.2.6 on 2022-02-19 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0009_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-square']},
        ),
    ]
