# Generated by Django 5.1.7 on 2025-04-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("houses", "0013_alter_project_square"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sauna",
            name="full_name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="sauna",
            name="short_name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=60, unique=True, verbose_name="Category's name"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, null=True, verbose_name="Category's slug"
                    ),
                ),
                (
                    "priority",
                    models.SmallIntegerField(default=1, verbose_name="Priority"),
                ),
                (
                    "subcategory",
                    models.ManyToManyField(
                        blank=True,
                        related_name="parent",
                        to="houses.category",
                        verbose_name="Subcategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ("priority", "name"),
            },
        ),
        migrations.AddField(
            model_name="house",
            name="category",
            field=models.ManyToManyField(
                blank=True,
                related_name="houses",
                to="houses.category",
                verbose_name="category",
            ),
        ),
        migrations.AddField(
            model_name="sauna",
            name="category",
            field=models.ManyToManyField(
                blank=True,
                related_name="saunas",
                to="houses.category",
                verbose_name="category",
            ),
        ),
    ]
