# Generated by Django 5.1.7 on 2025-04-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("houses", "0014_alter_sauna_full_name_alter_sauna_short_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="category",
            name="title",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
    ]
