# Generated by Django 5.1.7 on 2025-04-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("houses", "0015_category_description_category_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="category",
            field=models.ManyToManyField(
                blank=True,
                related_name="projects",
                to="houses.category",
                verbose_name="category",
            ),
        ),
    ]
