# Generated by Django 5.1.7 on 2025-04-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("houses", "0016_project_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="description",
            new_name="description_house",
        ),
        migrations.RenameField(
            model_name="category",
            old_name="title",
            new_name="title_house",
        ),
        migrations.AddField(
            model_name="category",
            name="description_sauna",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="category",
            name="title_sauna",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
    ]
