# Generated by Django 5.1.7 on 2025-05-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("houses", "0018_category_header_house_category_header_sauna_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="subcategories_description",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Subcategories description"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="header_house",
            field=models.TextField(
                blank=True, null=True, verbose_name="Header (house)"
            ),
        ),
    ]
