# Generated by Django 4.2 on 2025-07-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0019_category_subcategories_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('priority', 'name'), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Дом', 'verbose_name_plural': 'Дома'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['square'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='sauna',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Баня', 'verbose_name_plural': 'Бани'},
        ),
        migrations.AddField(
            model_name='house',
            name='price_per_m2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за м²'),
        ),
        migrations.AddField(
            model_name='sauna',
            name='price_per_m2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за м²'),
        ),
        migrations.AlterField(
            model_name='house',
            name='brus',
            field=models.CharField(max_length=20, verbose_name='Характеристика бруса'),
        ),
        migrations.AlterField(
            model_name='house',
            name='complex',
            field=models.TextField(blank=True, null=True, verbose_name='Комплектация'),
        ),
        migrations.AlterField(
            model_name='house',
            name='construction',
            field=models.CharField(max_length=20, verbose_name='Тип конструкции'),
        ),
        migrations.AlterField(
            model_name='house',
            name='cost',
            field=models.CharField(max_length=15, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='house',
            name='cover',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='house',
            name='description1',
            field=models.TextField(blank=True, null=True, verbose_name='Описание 1'),
        ),
        migrations.AlterField(
            model_name='house',
            name='description2',
            field=models.TextField(blank=True, null=True, verbose_name='Описание 2'),
        ),
        migrations.AlterField(
            model_name='house',
            name='dimensions',
            field=models.CharField(max_length=15, verbose_name='Габариты'),
        ),
        migrations.AlterField(
            model_name='house',
            name='full_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='URL название'),
        ),
        migrations.AlterField(
            model_name='house',
            name='images_count',
            field=models.IntegerField(verbose_name='Количество изображений'),
        ),
        migrations.AlterField(
            model_name='house',
            name='short_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='URL сокращ. название'),
        ),
        migrations.AlterField(
            model_name='house',
            name='slug',
            field=models.SlugField(max_length=300, unique=True, verbose_name='Короткий тег'),
        ),
        migrations.AlterField(
            model_name='house',
            name='square',
            field=models.CharField(max_length=15, verbose_name='Общая площадь (м²)'),
        ),
        migrations.AlterField(
            model_name='house',
            name='square1',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Доп. площадь 1'),
        ),
        migrations.AlterField(
            model_name='house',
            name='square2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Доп. площадь 2'),
        ),
        migrations.AlterField(
            model_name='house',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='house',
            name='video_url',
            field=models.CharField(max_length=20, verbose_name='Youtube URL видео'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='projects', to='houses.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='project',
            name='dimensions',
            field=models.CharField(max_length=15, verbose_name='Габариты'),
        ),
        migrations.AlterField(
            model_name='project',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='URL название'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_name',
            field=models.CharField(max_length=200, verbose_name='URL сокращ. название'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=300, unique=True, verbose_name='Короткий тег'),
        ),
        migrations.AlterField(
            model_name='project',
            name='square',
            field=models.FloatField(verbose_name='Общая площадь (м²)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='sauna',
            name='brus',
            field=models.CharField(max_length=20, verbose_name='Характеристика бруса'),
        ),
        migrations.AlterField(
            model_name='sauna',
            name='complex',
            field=models.TextField(blank=True, null=True, verbose_name='Комплектация'),
        ),
        migrations.AlterField(
            model_name='sauna',
            name='construction',
            field=models.CharField(max_length=20, verbose_name='Тип конструкции'),
        ),
        migrations.AlterField(
            model_name='sauna',
            name='cost',
            field=models.CharField(max_length=15, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='sauna',
            name='cover',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='sauna',
            name='description1',
            field=models.TextField(blank=True, null=True, verbose_name='Описание 1'),
        ),
        migrations.AlterField(
            model_name='sauna',
            name='description2',
            field=models.TextField(blank=True, null=True, verbose_name='Описание 2'),
        ),
        migrations.AlterField(
            model_name='sauna',
            name='dimensions',
            field=models.CharField(max_length=15, verbose_name='Габариты'),
        ),
        migrations.AlterField(
            model_name='sauna',
            name='full_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='URL название'),
        ),
        migrations.AlterField(
            model_name='sauna',
            name='images_count',
            field=models.IntegerField(verbose_name='Количество изображений'),
        ),
        migrations.AlterField(
            model_name='sauna',
            name='short_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='URL сокращ. название'),
        ),
        migrations.AlterField(
            model_name='sauna',
            name='slug',
            field=models.SlugField(max_length=300, unique=True, verbose_name='Короткий тег'),
        ),
        migrations.AlterField(
            model_name='sauna',
            name='square',
            field=models.CharField(max_length=15, verbose_name='Общая площадь (м²)'),
        ),
        migrations.AlterField(
            model_name='sauna',
            name='square1',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Доп. площадь 1'),
        ),
        migrations.AlterField(
            model_name='sauna',
            name='square2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Доп. площадь 2'),
        ),
        migrations.AlterField(
            model_name='sauna',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='sauna',
            name='video_url',
            field=models.CharField(max_length=20, verbose_name='Youtube URL видео'),
        ),
    ]
