# Generated by Django 4.2 on 2025-07-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0020_alter_category_options_alter_house_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='cost',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='house',
            name='price_per_m2',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Цена за м²'),
        ),
        migrations.AlterField(
            model_name='house',
            name='square',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Общая площадь (м²)'),
        ),
        migrations.AlterField(
            model_name='house',
            name='square1',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Доп. площадь 1'),
        ),
        migrations.AlterField(
            model_name='house',
            name='square2',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Доп. площадь 2'),
        ),
        migrations.AlterField(
            model_name='sauna',
            name='cost',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='sauna',
            name='price_per_m2',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Цена за м²'),
        ),
        migrations.AlterField(
            model_name='sauna',
            name='square',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Общая площадь (м²)'),
        ),
        migrations.AlterField(
            model_name='sauna',
            name='square1',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Доп. площадь 1'),
        ),
        migrations.AlterField(
            model_name='sauna',
            name='square2',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Доп. площадь 2'),
        ),
    ]
