# Generated by Django 4.2 on 2025-07-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0021_alter_house_cost_alter_house_price_per_m2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='square1',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Доп. площадь 1'),
        ),
        migrations.AlterField(
            model_name='house',
            name='square2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Доп. площадь 2'),
        ),
        migrations.AlterField(
            model_name='sauna',
            name='square1',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Доп. площадь 1'),
        ),
        migrations.AlterField(
            model_name='sauna',
            name='square2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Доп. площадь 2'),
        ),
    ]
