# Generated by Django 4.2 on 2025-07-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0022_alter_house_square1_alter_house_square2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='cost',
            field=models.IntegerField(verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='house',
            name='price_per_m2',
            field=models.IntegerField(default=0, verbose_name='Цена за м²'),
        ),
        migrations.AlterField(
            model_name='house',
            name='square',
            field=models.BigIntegerField(verbose_name='Общая площадь (м²)'),
        ),
        migrations.AlterField(
            model_name='sauna',
            name='cost',
            field=models.IntegerField(verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='sauna',
            name='price_per_m2',
            field=models.IntegerField(default=0, verbose_name='Цена за м²'),
        ),
        migrations.AlterField(
            model_name='sauna',
            name='square',
            field=models.BigIntegerField(verbose_name='Общая площадь (м²)'),
        ),
    ]
