# Generated by Django 4.2 on 2025-07-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0023_alter_house_cost_alter_house_price_per_m2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='square',
            field=models.FloatField(verbose_name='Общая площадь (м²)'),
        ),
        migrations.AlterField(
            model_name='sauna',
            name='square',
            field=models.FloatField(verbose_name='Общая площадь (м²)'),
        ),
    ]
