# Generated by Django 4.2 on 2025-08-04 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0024_alter_house_square_alter_sauna_square'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='construction',
            field=models.CharField(max_length=20, verbose_name='Время изготовления'),
        ),
        migrations.AlterField(
            model_name='house',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='sauna',
            name='construction',
            field=models.CharField(max_length=20, verbose_name='Время изготовления'),
        ),
        migrations.AlterField(
            model_name='sauna',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
        migrations.CreateModel(
            name='SaunaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/structure/', verbose_name='Изображение')),
                ('alt', models.CharField(blank=True, max_length=255, verbose_name='alt-текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='houses.sauna', verbose_name='Баня')),
            ],
            options={
                'verbose_name': 'Фото бани',
                'verbose_name_plural': 'Фото бани',
            },
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/structure/', verbose_name='Изображение')),
                ('alt', models.CharField(blank=True, max_length=255, verbose_name='alt-текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='houses.house', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Фото дома',
                'verbose_name_plural': 'Фото дома',
            },
        ),
    ]
