# Generated by Django 4.2 on 2025-08-10 15:57

from django.db import migrations, models
import houses.models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0025_alter_house_construction_alter_house_pub_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseimage',
            name='is_cover',
            field=models.BooleanField(default=False, verbose_name='Обложка'),
        ),
        migrations.AddField(
            model_name='saunaimage',
            name='is_cover',
            field=models.BooleanField(default=False, verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='houseimage',
            name='image',
            field=models.ImageField(upload_to=houses.models._upload_to_structure, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='houseimage',
            name='order',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Порядок отображения'),
        ),
        migrations.AlterField(
            model_name='saunaimage',
            name='image',
            field=models.ImageField(upload_to=houses.models._upload_to_structure, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='saunaimage',
            name='order',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Порядок отображения'),
        ),
        migrations.AlterUniqueTogether(
            name='houseimage',
            unique_together={('structure', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='saunaimage',
            unique_together={('structure', 'order')},
        ),
    ]
