# Generated by Django 4.2 on 2025-08-10 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0026_houseimage_is_cover_saunaimage_is_cover_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='sauna',
            name='cover',
        ),
    ]
