# Generated by Django 4.2 on 2025-09-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0027_remove_house_cover_remove_sauna_cover'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='houseimage',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='saunaimage',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='house',
            name='images_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество изображений, не обязательное'),
        ),
        migrations.AlterField(
            model_name='house',
            name='price_per_m2',
            field=models.IntegerField(choices=[(100000, '100 000 ₽/м² (до 70 м²)'), (90000, '90 000 ₽/м² (70–150 м²)'), (80000, '80 000 ₽/м² (свыше 150 м²)')], default=100000, verbose_name='Цена за м²'),
        ),
        migrations.AlterField(
            model_name='houseimage',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок отображения'),
        ),
        migrations.AlterField(
            model_name='sauna',
            name='images_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество изображений, не обязательное'),
        ),
        migrations.AlterField(
            model_name='sauna',
            name='price_per_m2',
            field=models.IntegerField(choices=[(100000, '100 000 ₽/м² (до 70 м²)'), (90000, '90 000 ₽/м² (70–150 м²)'), (80000, '80 000 ₽/м² (свыше 150 м²)')], default=100000, verbose_name='Цена за м²'),
        ),
        migrations.AlterField(
            model_name='saunaimage',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок отображения'),
        ),
        migrations.AddConstraint(
            model_name='houseimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_cover', True)), fields=('structure',), name='unique_house_cover_per_structure'),
        ),
        migrations.AddConstraint(
            model_name='houseimage',
            constraint=models.UniqueConstraint(fields=('structure', 'order'), name='unique_house_structure_order'),
        ),
        migrations.AddConstraint(
            model_name='saunaimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_cover', True)), fields=('structure',), name='unique_sauna_cover_per_structure'),
        ),
        migrations.AddConstraint(
            model_name='saunaimage',
            constraint=models.UniqueConstraint(fields=('structure', 'order'), name='unique_sauna_structure_order'),
        ),
    ]
