# Generated by Django 4.2 on 2025-09-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0028_alter_houseimage_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='sauna',
            name='cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стоимость'),
        ),
    ]
