# Generated by Django 4.2 on 2025-09-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0029_alter_house_cost_alter_sauna_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='rutube_video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Rutube видео'),
        ),
        migrations.AddField(
            model_name='house',
            name='vk_video_url',
            field=models.URLField(blank=True, null=True, verbose_name='VK видео для фрейма'),
        ),
        migrations.AddField(
            model_name='sauna',
            name='rutube_video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Rutube видео'),
        ),
        migrations.AddField(
            model_name='sauna',
            name='vk_video_url',
            field=models.URLField(blank=True, null=True, verbose_name='VK видео для фрейма'),
        ),
        migrations.AlterField(
            model_name='house',
            name='images_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество изображений, не заполнять'),
        ),
        migrations.AlterField(
            model_name='sauna',
            name='images_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество изображений, не заполнять'),
        ),
    ]
