# Generated by Django 4.2 on 2025-09-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0030_house_rutube_video_url_house_vk_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='video_url',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Youtube URL видео'),
        ),
        migrations.AlterField(
            model_name='sauna',
            name='video_url',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Youtube URL видео'),
        ),
    ]
