# Generated by Django 4.2 on 2025-09-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0031_alter_house_video_url_alter_sauna_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_visible',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Попадает в выборку'),
        ),
    ]
