# Generated by Django 4.2 on 2025-10-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0032_category_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_floor',
            field=models.BooleanField(default=False, verbose_name='Категория по этажности'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_selection',
            field=models.BooleanField(default=False, verbose_name='Категория-подборка'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_size',
            field=models.BooleanField(default=False, verbose_name='Категория по размеру'),
        ),
    ]
